FROM node:19.2.0-alpine3.16
RUN set -x \
  && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
  && apk upgrade \
  && apk --no-cache add alpine-sdk bash libstdc++ libc6-compat \
  && npm config set python python3 
RUN git clone --recursive https://github.com/cdr/code-server.git
RUN cd code-server
RUN yarn global add code-server

ENV PASSWORD=changeme
ENTRYPOINT code-server --bind-addr 0:8443
