FROM ubuntu:20.04
LABEL com.repasscloud.image.authors="hello@repasscloud.com"
RUN apt update && \
  DEBIAN_FRONTEND=noninteractive apt install -y kubuntu-desktop xrdp && \
  adduser xrdp ssl-cert

RUN useradd -m testuser -p $(openssl passwd 1234) && \
  usermod -aG sudo testuser

EXPOSE 3389

CMD service dbus start ; /usr/lib/systemd/systemd-logind & service xrdp start ; bash
