name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Ubuntu 20.04 Apache
      run: docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:apache ./ubuntu-20.04/apache
