name: Docker Image CI

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04 apache
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:apache --file ./ubuntu/20.04/Dockerfile.apache ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:apache
    - name: ubuntu 20.04 kubuntu-rdp
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:kubuntu-rdp --file ./ubuntu/20.04/Dockerfile.kubuntu-rdp ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:kubuntu-rdp
    - name: ubuntu 20.04 vscode
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:vscode --file ./ubuntu/20.04/Dockerfile.vscode ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:vscode

  alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Alpine 3.16 httpd
      run: |
        docker build --rm --no-cache --tag repasscloud/alpine-3.16:httpd --file ./alpine/3.16/Dockerfile.httpd ./alpine/3.16
        docker push repasscloud/alpine-3.16:httpd
