name: Docker Image CI

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path ./ubuntu/20.04/ -Filter "Dockerfile.*"
        foreach ($f in $files)
        {
            $filename = $f.Name
            $filepath = $f.FullName
            $ext = $f.Name.Split('.')[1]
            docker build --rm --no-cache --tag "repasscloud/ubuntu-20.04:${ext}" --file $filename ./ubuntu/20.04
        }

  alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Alpine 3.16 httpd
      run: |
        docker build --rm --no-cache --tag repasscloud/alpine-3.16:httpd --file ./alpine/3.16/Dockerfile.httpd ./alpine/3.16
        docker push repasscloud/alpine-3.16:httpd
