name: Docker Image CI

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04
      shell: pwsh
      run: |
        [string]$dfiles = Get-ChildItem -Path ./ubuntu/20.04 -File -Filter "Dockerfile.*"
        foreach ($dfile in $dfiles) {
          $fname = $dfile.Name; $fpath = $dfile.FullName; $img = $dfile.Name.Split('.')[1];
          docker build --rm --no-cache --tag "repasscloud/ubuntu-20.04:${img}" --file $fpath ./ubuntu/20.04;
          docker push "repasscloud/ubuntu-20.04:${img}"
        }

  alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Alpine 3.16 httpd
      run: |
        docker build --rm --no-cache --tag repasscloud/alpine-3.16:httpd --file ./alpine/3.16/Dockerfile.httpd ./alpine/3.16
        docker push repasscloud/alpine-3.16:httpd

       
