name: ubuntu

on:
  schedule:
    - cron: '0 3 * * 2'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  ubuntu-2004-apache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04 apache
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:apache --file ./ubuntu/20.04/Dockerfile.apache ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:apache

  ubuntu-2004-kubuntu-rdp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04 kubuntu-rdp
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:kubuntu-rdp --file ./ubuntu/20.04/Dockerfile.kubuntu-rdp ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:kubuntu-rdp

  ubuntu-2004-vscode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ubuntu 20.04 vscode
      run: |
        docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:vscode --file ./ubuntu/20.04/Dockerfile.vscode ./ubuntu/20.04
        docker push repasscloud/ubuntu-20.04:vscode
