name: Docker Image CI

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Ubuntu 20.04
      run: docker build --rm --no-cache --tag repasscloud/ubuntu-20.04:apache --file Dockerfile.apache ./ubuntu/20.04

  alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Alpine 3.16
      run: docker build --rm --no-cache --tag repasscloud/alpine-3.16:httpd --file Dockerfile.httpd ./alpine/3.16
